### ISSUE TITLE
Cant get connection when debugging using XRM Test project

### ISSUE THREAD

**Issue by i8sy72** [josephmcmac/JM-Dataverse-Toolbelt#386]
I have freshly installed the Extension into visual studio 2022 from the marketplace ( version 3.2.0.0 )
I have setup my credentials using the XRM Tooling connector , I can successfully update my schema.cs file and deploy/update etc

 I have made a TestMethod 
```C#
[TestMethod]
public void XrmTest1Test()
{
    XrmService.WhoAmI();
}
```

but when I debug I get 
System.Exception: 'Error connecting to crm instance - check your crm connection details'

```C#
public IOrganizationService GetOrganisationConnection()
{
    try
    {
        var conn = $"AuthType=ClientSecret;url={CrmConfig.WebUrl};ClientId={CrmConfig.ClientId};ClientSecret={CrmConfig.ClientSecret}";

        return new CrmServiceClient(conn);
    }
    catch (Exception ex)
    {
        throw new Exception("Error connecting to crm instance - check your crm connection details", ex); // error thrown here
    }
}

```

this is only looking for client secret type connection... so I attempted a client secret connection but get error in image 
![image](https://github.com/user-attachments/assets/437c00a4-528b-40e8-ac6c-f2b61c4bb35e)

**Comment by josephmcmac** [comment]
Hi i8sy72.

Probably your client and secret is not valid to log into the instance. In the Dataverse instance you're connecting to. Hve you created an application with a security role for that app registration?

The next release version should have a better error message when creating a connection for a client secret, as I have implemented it is part of #381. I'm hoping to release that new version soon. 

For the test project, you're correct it only works for client secret connections. As you haven't successfully created a client secret connection, I think the CrmServiceClient will be throwing that error due to an invalid connection string with no client and secret details. If you hardcode the client and secret, you should be able to get the actual connection error for your client secret using the LastCrmError property of the CrmServiceClient once it tries to perform an operation against the web service. This is what I did for the enhancement #381 
https://learn.microsoft.com/en-us/dotnet/api/microsoft.xrm.tooling.connector.crmserviceclient.lastcrmerror?view=dataverse-sdk-latest
